### PR TITLE
removed repetitive comments

### PR DESCRIPTION
**Pull request by jaykay99992**
Removed repeated comments that explains the params m , app , v. Only kept the definitions for the first time they are declared.

I also removed the "mostly used" comments for each method and kept what it does , for code clarity.

### CODE REVIEW

**Comment by Fch1995** [comment]
The code has become cleaner and more readable due to the modification. Importantly, this change does not alter the workflow of the code; it maintains the same functionality as the original while improving its clarity. I endorse this modification as it enhances the overall maintainability and understanding of the code without impacting its intended behavior."

**Comment by jaykay99992** [comment]
@Fch1995 Thank you for the remarks, just to confirm, do I proceed to merge the code ?

**Comment by Fch1995** [comment]
@jaykay99992 yes, yes , merge it!

**Comment by jaykay9999** [comment]
Sure, code merged

**Pull request merged**
