### PR TITLE
changed variables definition to final

### PR DESCRIPTION
**Pull request by jaykay99992**
I added the "final" to variable definitions to ensure that they cannot be changed after being assigne

### CODE REVIEW

**Comment by fcb29000** [comment]
If you are planning to declare a final variable as a class parameter, make sure to assign a value to it at the declaration stage or within the constructor of the class. Otherwise you will get a compilation error. 
If you are, however, declaring a final variable in the 'main' method, you must assign it a value at declaration, because there are no constructors for the main method.

**Review by zchafik — APPROVED** [review]
The changes represents a good refactoring. Here are some  positif points :
Removal of duplicate declarations, Using the final keyword, liminating compilation errors and Improved readability.
Overall, these changes helped make the code cleaner, readable, and free of compilation errors, which is a positive indication of good refactoring.

**Comment by jaykay9999** [comment]
@zchafik Just a final confirmation, do I merge the code?

**Comment by fcb29000** [comment]
@jaykay9999 Yes Merge it! 
When you are using final, you are protecting your variables from being changed after assigning a value, and the latter could only be done at the declaration stage or in the constructor of the class. So the first part(line 23,24,25) is indeed correct. As per declaring final for parameters in the function(the remaining lines), you are being extra cautious, but it is feasible and you will experience no errors

**Comment by jaykay9999** [comment]
Code merged

**Pull request merged**
