### PR TITLE
one return statement at the end, instead of two

### PR DESCRIPTION
**Pull request by jaykay99992**
I refactored the function to declare a variable in the beginning , then modify that variable based on the if else conditions, and return the modified variable, to avoid having multiple return statements.

### CODE REVIEW

**Comment by etienne-tillier** [comment]
It's good to just have one return for a function, but your method can return two diferent types of object. I guess that's why the function return an Object type but is it good ?

**Comment by etienne-tillier** [comment]
So for me, if it's good for you in this project to have this function returning an object type, you can merge the changes on the main branch.

**Comment by jaykay99992** [comment]
> It's good to just have one return for a function, but your method can return two diferent types of object. I guess that's why the function return an Object type but is it good ?

Thank you, and that was my reasoning too, since Object englobes to some extent all types of objects.

**Comment by jaykay9999** [comment]
pull request merged.

**Pull request merged**
