### PR TITLE
Refactored getIcon() to remove repetitive code

### PR DESCRIPTION
**Pull request by jaykay99992**
this part of each case in the switch statement :

    if (iconName == null) {
      return null;
    }
    if (icon == null) {
      return loadImage(iconName);
    }
    return icon;
    
    is repetitive, so I created a seperate function for it, loadImage() and call that function multiple times instead.

### CODE REVIEW

**Comment by socrate-01** [comment]
This is excellent, as it improves code readability and facilitates maintenance by reducing duplication.
Have you tested these changes in different scenarios to confirm that no regression has been introduced, particularly in loading and displaying icons?

**Comment by jaykay99992** [comment]
@socrate-01 so far tested the same code functionality in a different environment and it give the same results in both scenarios (before the changes and after the changes). Should I proceed and merge it?

**Comment by socrate-01** [comment]
I think yes you should merge it cause it's great actually

**Comment by jaykay9999** [comment]
Code approved and merged

**Pull request merged**
