### PR TITLE
turned multiple if's to if else statements

### PR DESCRIPTION
**Pull request by jaykay99992**
I noticed that multiple if statements for conditions that cover null , or NOT null, therefore I refactored it to multiple if , else statements.

### CODE REVIEW

**Comment by LinkinFoxco** [comment]
Could arguably make the code harder to read.
Probably could use a loop using a list of the parent object and and override a "createMenu()" function.

**Review by LinkinFoxco — CHANGES_REQUESTED** [review]
Could arguably make the code harder to read.
Probably could use a loop using a list of the parent object and and override a "createMenu()" function.

**Comment by jaykay99992** [comment]
@LinkinFoxco I just introduced a menuObject class and called it inside the loop. As for the "this::" operator, It is used to call a method by referring to it, here is a link that explains it in depth : https://www.geeksforgeeks.org/double-colon-operator-in-java/ 

Do I merge the changes like this ?

**Review by LinkinFoxco — APPROVED** [review]
Make sure it works properly since you don't have tests but it looks good to me !

**Comment by jaykay9999** [comment]
Sure, code merged

**Pull request merged**
