### PR TITLE
Introduced a loop to create the buttons

### PR DESCRIPTION
**Pull request by jaykay99992**
Instead of adding each button manually with having the scaleFactor parameter as the only paramater changing, I introduced a loop that increases the scaleFactor in accordance to the existing code, without having to declare each button in a new line

### CODE REVIEW

**Comment by etienne-tillier** [comment]
This refactor is good but it will change the execution of the code. In fact, in the old implementation you are not all the time incrementing the parameter by 0,25 but in your loop that's the case. So you should change the loop with a condition inside to increase the zoomLevel value as you need. 

A possible solution for your loop : 

`    for (double zoomLevel = 0.25; zoomLevel <= 4.0; zoomLevel += 0.25) {
      if (zoomLevel == 1.0) {
        m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null)));
        rbmi.setSelected(true);
        group.add(rbmi);
      } else if(zoomLevel == 1.5) {
zoomLevel += 0,25
}
      } else if(zoomLevel >= 2) {
zoomLevel += 0,75
}
else {
        m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null)));
        group.add(rbmi);
      }
    }
`

I think that's not an optimal solution because there is a lot of condition in the loop, but that's refactor solution while your is not because it's changing the execution.

**Comment by jaykay99992** [comment]
> This refactor is good but it will change the execution of the code. In fact, in the old implementation you are not all the time incrementing the parameter by 0,25 but in your loop that's the case. So you should change the loop with a condition inside to increase the zoomLevel value as you need.
> 
> A possible solution for your loop :
> 
> ` for (double zoomLevel = 0.25; zoomLevel <= 4.0; zoomLevel += 0.25) { if (zoomLevel == 1.0) { m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); rbmi.setSelected(true); group.add(rbmi); } else if(zoomLevel == 1.5) { zoomLevel += 0,25 } } else if(zoomLevel >= 2) { zoomLevel += 0,75 } else { m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); group.add(rbmi); } }`
> 
> I think that's not an optimal solution because there is a lot of condition in the loop, but that's refactor solution while your is not because it's changing the execution.

So do you recommend that I use your possible solution for the pull request ?

**Comment by etienne-tillier** [comment]
`for (double zoomLevel = 0.25; zoomLevel <= 4.0; zoomLevel += 0.25) 
{
 if (zoomLevel == 1.0) { 
m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); 
rbmi.setSelected(true);
 group.add(rbmi);
 } 
else if(zoomLevel == 1.5) { 
zoomLevel += 0,25 
m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); group.add(rbmi); 
} 
else if(zoomLevel >= 2) { 
zoomLevel += 0,75 
m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); group.add(rbmi); 
} 
else { 
m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); group.add(rbmi); 
}
 }`
 
 This one is fine i changed things because i forgot to add objects to m object. I think you can see if there is some errors first by compiling the code and testing and then you can merge it if everything is good !

**Comment by jaykay99992** [comment]
> `for (double zoomLevel = 0.25; zoomLevel <= 4.0; zoomLevel += 0.25) { if (zoomLevel == 1.0) { m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); rbmi.setSelected(true); group.add(rbmi); } else if(zoomLevel == 1.5) { zoomLevel += 0,25 m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); group.add(rbmi); } else if(zoomLevel >= 2) { zoomLevel += 0,75 m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); group.add(rbmi); } else { m.add(rbmi = new JRadioButtonMenuItem(new ZoomAction(editor, zoomLevel, null))); group.add(rbmi); } }`
> 
> This one is fine i changed things because i forgot to add objects to m object. I think you can see if there is some errors first by compiling the code and testing and then you can merge it if everything is good !

I added your code, with minor changes. 

1-  int variables like 0,25 to 0.25 ( . instead of a ,) and I also added some ";" since java needs those at the end of every line.

**Pull request merged**
